version: '3.3'
 
services:
  abn_movies_app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    container_name: abn_movies_app
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./build:/app/build
      - ./package.json:/app/package.json
      - ./public:/app/public
      - ./tsconfig.json:/app/tsconfig.json
      - ./node_modules:/app/node_modules
      - ./.eslintrc.json:/app/.eslintrc.json
      - ./jest.config.ts:/app/jest.config.ts
      - ./jest.setup.ts:/app/jest.setup.ts
    tty: true
    ports:
      - "8080:8080"